name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy-infra:
    environment: production
    env:
      TF_VAR_mnemonic: ${{ secrets.MNEMONIC }}
      TF_VAR_discord_webhook_key: ${{ secrets.DISCORD_WEBHOOK_KEY }}
      
    
    #  Enable these if you want to use the discord/telegram/betteruptime integrations

    #   TF_VAR_telegram_api_key: ${{ secrets.TELEGRAM_API_KEY }}
    #   TF_VAR_telegram_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
    #   TF_VAR_betteruptime_api_key: ${{ secrets.BETTERUPTIME_API_KEY }}
    #   TF_VAR_betteruptime_requester_email: ${{ secrets.BETTERUPTIME_REQUESTER_EMAIL }}
    
    #  Currently not used, but might be in the future

    #   TF_VAR_admin_token_watcher: ${{ secrets.ADMIN_TOKEN_WATCHER }}

      IMAGE_NAME: connext/router-publisher
    runs-on: ubuntu-latest
    name: Deploy Infra to AWS
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - name: Set up Terraform Version
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=tfvars.json

      - name: Terraform Deploy
        run: terraform apply -var-file=tfvars.json -auto-approve
